# Generated by Django 3.0.5 on 2020-05-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('publisher', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'video',
                'db_table': 'video',
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title', 'description'], name='video_title_5fe4b2_idx'),
        ),
    ]
